; https://docs.platformio.org/page/projectconf.html

; Flash: 16MB QD, PSRAM: 8MB OT
;https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ===============================
; Flash configuration (CRITICAL)
; ===============================
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.flash_freq = 40m

; ===============================
; PSRAM configuration (OPI)
; ===============================
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.extra_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_USE_MALLOC
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DCONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY

; ===============================
; Partition table
; ===============================
board_build.partitions = default_16MB.csv


; ===============================
; Upload / monitor
; ===============================
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; ===============================
; Libraries
; ===============================
lib_deps =
    adafruit/Adafruit GFX Library@^1.12.0
    okbao/ST7565 LCD@^1.0.2